blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/giuseppesalvi/nvim-ascii-animation/discussions
    about: Ask questions and discuss ideas here instead of opening an issue
